#!/bin/zsh

# Installation script for gtp
# This script creates a modified gtp script with absolute paths and installs it to /usr/bin

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
GTP_SOURCE="$SCRIPT_DIR/gtp"
PYTHON_SCRIPT="$SCRIPT_DIR/go_to_project.py"
CONFIG_FILE="$SCRIPT_DIR/config.json"
USER_HOME=$(eval echo "~$SUDO_USER")
BASHRC="$USER_HOME/.bashrc"
ZSHRC="$USER_HOME/.zshrc"

# Check if source files exist
if [ ! -f "$GTP_SOURCE" ]; then
    echo "❌ Error: gtp script not found at $GTP_SOURCE"
    exit 1
fi

if [ ! -f "$PYTHON_SCRIPT" ]; then
    echo "❌ Error: go_to_project.py not found at $PYTHON_SCRIPT"
    exit 1
fi

if [ ! -f "$CONFIG_FILE" ]; then
    echo "❌ Error: config.json not found at $CONFIG_FILE"
    exit 1
fi

# Check if running as root or with sudo
if [ "$EUID" -ne 0 ]; then
    echo "🔐 This script requires root privileges to install to /usr/bin"
    echo "📝 Please run: sudo ./install.sh"
    exit 1
fi

# Create a temporary modified gtp script with absolute paths
TEMP_GTP="/tmp/gtp_install_$$"

cat > "$TEMP_GTP" << EOF
#!/bin/zsh

# Wrapper script for go_to_project.py
# This ensures the directory change persists in the current shell
# Auto-generated by install.sh with absolute paths

if [ -z "\$1" ]; then
    echo "Usage: gtp <project_name>"
    exit 1
fi

PYTHON_SCRIPT="$PYTHON_SCRIPT"
TEMP_SCRIPT="/tmp/gtp_\$1.sh"

# Run the Python script and generate commands to execute
python3 "\$PYTHON_SCRIPT" "\$1"

# If the script was generated successfully, source it
if [ -f "\$TEMP_SCRIPT" ]; then
    chmod +x "\$TEMP_SCRIPT"
    source "\$TEMP_SCRIPT"
    rm -f "\$TEMP_SCRIPT"
else
    echo "❌ No script generated for project '\$1'"
fi
EOF

# Copy the modified script to /usr/bin
echo "📦 Installing gtp to /usr/bin with absolute paths..."
cp "$TEMP_GTP" /usr/bin/gtp

# Make sure it's executable
chmod +x /usr/bin/gtp

# Clean up temporary file
rm -f "$TEMP_GTP"

# Add alias to .zshrc/.bashrc for convenience
echo "Do you want to add the 'gtp' alias to your shell config?"
echo "1) $BASHRC"
echo "2) $ZSHRC"
echo "3) No, I'll do it manually or use 'source /usr/bin/gtp' each time"
printf "Choose an option [1/2/3]: "
read choice

case "$choice" in
    1)
        if ! grep -q "alias gtp='source /usr/bin/gtp'" $BASHRC; then
            echo "Adding alias to $BASHRC for convenience..."
            echo "alias gtp='source /usr/bin/gtp'" >> $BASHRC
            echo "Please restart your terminal or run 'source $BASHRC' to apply changes."
        else
            echo "Alias already exists in $BASHRC"
        fi
    ;;
    2)
        if ! grep -q "alias gtp='source /usr/bin/gtp'" $ZSHRC; then
            echo "Adding alias to $ZSHRC for convenience..."
            echo "alias gtp='source /usr/bin/gtp'" >> $ZSHRC
            echo "Please restart your terminal or run 'source $ZSHRC' to apply changes."
        else
            echo "Alias already exists in $ZSHRC"
        fi
    ;;
    *)
        echo "No alias added. You can add it manually or use 'source /usr/bin/gtp' each time."
    ;;
esac

# Verify installation
if [ -f "/usr/bin/gtp" ]; then
    echo "✅ gtp successfully installed to /usr/bin"
    echo "📁 Python script path: $PYTHON_SCRIPT"
    echo "📁 Config file path: $CONFIG_FILE"
    echo "📖 You can now use 'gtp <project_name>' from anywhere"
else
    echo "❌ Installation failed"
    exit 1
fi
